In [1]:
import numpy as np
import pandas as pd
from scipy.stats import pearsonr
import seaborn as sn
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('DataSetPrimer.csv')
df.index = df.id
df = df.drop(['id', 'action', 'video_src'], axis = 1)
df = df.fillna(0)
df

Nose_x0  Nose_y0  Neck_x1  Neck_y1  RShoulder_x2  RShoulder_y2  \
id                                                                    
990      150       20      157       29           156            28   
991      148       20      156       29           156            27   
992      145       19      153       29           153            27   
993      143       19      150       29           149            28   
994      140       18      147       28           147            27   
995      138       18      146       27           144            26   
996      135       18      143       27           141            25   
997      133       16      141       27           139            25   
998      130       17      138       27           138            25   
999      127       17      135       27           134            25   

     Relbow_x3  RElbow_y3  RWrist_x4  RWrist_y4  ...  LAnkle_x13  LAnkle_y13  \
id                                               ...                           
990      153.0       40.0      147.0       51.0  ...         0.0         0.0   
991      151.0       42.0        0.0        0.0  ...       139.0        95.0   
992        0.0        0.0        0.0        0.0  ...       139.0        96.0   
993      144.0       44.0        0.0        0.0  ...       138.0        96.0   
994      140.0       42.0        0.0        0.0  ...       138.0        97.0   
995        0.0        0.0        0.0        0.0  ...       138.0        97.0   
996        0.0        0.0        0.0        0.0  ...       139.0        95.0   
997        0.0        0.0        0.0        0.0  ...       138.0        95.0   
998        0.0        0.0        0.0        0.0  ...       138.0        95.0   
999      129.0       42.0      123.0       48.0  ...       138.0        95.0   

     REye_x14  REye_y14  LEye_x15  LEye_y15  REar_x16  REar_y16  LEar_x17  \
id                                                                          
990       0.0       0.0       152        18       0.0       0.0       156   
991       0.0       0.0       150        18       0.0       0.0       154   
992       0.0       0.0       147        18       0.0       0.0       151   
993       0.0       0.0       144        18       0.0       0.0       149   
994       0.0       0.0       141        17       0.0       0.0       147   
995       0.0       0.0       139        16       0.0       0.0       144   
996       0.0       0.0       136        16       0.0       0.0       141   
997       0.0       0.0       134        15       0.0       0.0       139   
998       0.0       0.0       132        15       0.0       0.0       136   
999       0.0       0.0       129        16       0.0       0.0       133   

     LEar_y17  
id             
990        18  
991        20  
992        19  
993        18  
994        18  
995        18  
996        17  
997        16  
998        16  
999        17  

[10 rows x 36 columns]

In [5]:
d = df.values
d[:1]

array([[150.,  20., 157.,  29., 156.,  28., 153.,  40., 147.,  51.,   0.,
          0.,   0.,   0.,   0.,   0., 152.,  60., 145.,  77., 140.,  95.,
        155.,  59.,   0.,   0.,   0.,   0.,   0.,   0., 152.,  18.,   0.,
          0., 156.,  18.]])

In [10]:
R = df.as_matrix()
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R_demeaned

C:\Users\Zhastay\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[ 9.00555556e+01, -3.99444444e+01,  9.70555556e+01,
        -3.09444444e+01,  9.60555556e+01, -3.19444444e+01,
         9.30555556e+01, -1.99444444e+01,  8.70555556e+01,
        -8.94444444e+00, -5.99444444e+01, -5.99444444e+01,
        -5.99444444e+01, -5.99444444e+01, -5.99444444e+01,
        -5.99444444e+01,  9.20555556e+01,  5.55555556e-02,
         8.50555556e+01,  1.70555556e+01,  8.00555556e+01,
         3.50555556e+01,  9.50555556e+01, -9.44444444e-01,
        -5.99444444e+01, -5.99444444e+01, -5.99444444e+01,
        -5.99444444e+01, -5.99444444e+01, -5.99444444e+01,
         9.20555556e+01, -4.19444444e+01, -5.99444444e+01,
        -5.99444444e+01,  9.60555556e+01, -4.19444444e+01],
       [ 6.53333333e+01, -6.26666667e+01,  7.33333333e+01,
        -5.36666667e+01,  7.33333333e+01, -5.56666667e+01,
         6.83333333e+01, -4.06666667e+01, -8.26666667e+01,
        -8.26666667e+01,  7.33333333e+01, -5.36666667e+01,
         6.93333333e+01, -3.96666667e+01,  6.53333333e+

In [19]:
user_ratings_mean

array([59.94444444, 82.66666667, 70.36111111, 74.83333333, 67.77777778,
       68.69444444, 67.44444444, 71.22222222, 70.27777778, 79.47222222])

In [46]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 1)

In [47]:
sigma = np.diag(sigma)

In [52]:
user_ratings_mean

array([59.94444444, 82.66666667, 70.36111111, 74.83333333, 67.77777778,
       68.69444444, 67.44444444, 71.22222222, 70.27777778, 79.47222222])

In [60]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df.columns)

In [61]:
preds_df

Nose_x0    Nose_y0     Neck_x1    Neck_y1  RShoulder_x2  RShoulder_y2  \
0  104.584296  24.437019  109.716566  30.890214    109.124776     29.815534   
1  155.844046  24.459924  164.257293  35.038542    163.287180     33.276836   
2  142.936073  12.633544  151.280060  23.125075    150.317933     21.377872   
3  144.075196  19.756979  152.035975  29.766673    151.118035     28.099713   
4  136.145531  13.396708  144.005812  23.280039    143.099461     21.634123   
5  139.569266  12.319202  147.717787  22.564959    146.778199     20.858686   
6  137.035650  12.090216  145.036593  22.150411    144.114022     20.475041   
7  139.400704  16.991703  147.239225  26.847673    146.335382     25.206313   
8  137.129375  17.102689  144.815343  26.766843    143.929091     25.157427   
9  137.747601  33.118828  144.447556  41.543192    143.674999     40.140244   

   Relbow_x3  RElbow_y3  RWrist_x4  RWrist_y4  ...  LAnkle_x13  LAnkle_y13  \
0  57.479563  25.638591  26.145832  17.455322  ...   98.080660   71.644141   
1  78.626026  26.429641  27.261154  13.014943  ...  145.182741  101.845789   
2  66.353735  14.587045  15.411713   1.282780  ...  132.362536   89.382345   
3  71.010001  21.620763  22.407557   8.927515  ...  133.987262   92.980992   
4  64.002711  15.236963  16.013825   2.703955  ...  126.184947   85.696341   
5  64.780945  14.226941  15.032290   1.234342  ...  129.243424   87.270087   
6  63.601822  13.963403  14.754167   1.206114  ...  126.896820   85.683663   
7  67.457606  18.826864  19.601575   6.328551  ...  129.467695   89.091179   
8  66.586429  18.902134  19.661767   6.647063  ...  127.389681   87.798970   
9  76.254427  34.687427  35.349609  24.004527  ...  129.257387   94.745666   

    REye_x14   REye_y14    LEye_x15   LEye_y15   REar_x16   REar_y16  \
0  12.361290  12.361290  105.565476  23.446186  12.361290  12.361290   
1   4.664378   4.664378  157.452478  22.835667   4.664378   4.664378   
2  -6.999040  -6.999040  144.531264  11.022657  -6.999040  -6.999040   
3   1.026048   1.026048  145.597126  18.220075   1.026048   1.026048   
4  -5.097764  -5.097764  137.648248  11.879206  -5.097764  -5.097764   
5  -6.853468  -6.853468  141.127088  10.746053  -6.853468  -6.853468   
6  -6.735218  -6.735218  138.565259  10.545558  -6.735218  -6.735218   
7  -1.451569  -1.451569  140.899261  15.478401  -1.451569  -1.451569   
8  -0.981641  -0.981641  138.598767  15.618839  -0.981641  -0.981641   
9  17.354490  17.354490  139.028488  31.825337  17.354490  17.354490   

     LEar_x17   LEar_y17  
0  108.639369  24.140882  
1  162.491462  23.974471  
2  149.528765  12.152086  
3  150.365110  19.297634  
4  142.356041  12.943161  
5  146.007518  11.849024  
6  143.357299  11.628553  
7  145.594021  16.539411  
8  143.202158  16.659200  
9  143.041322  32.732233  

[10 rows x 36 columns]

In [62]:
def vizio(df, pred, _index):
    corr, _ = pearsonr(df.values[_index], pred.values[_index])
    print('Pearsons correlation: %.3f' % corr)

In [63]:
for i in range(10):
    vizio(df, preds_df, i)

Pearsons correlation: 0.549
Pearsons correlation: 0.955
Pearsons correlation: 0.914
Pearsons correlation: 0.901
Pearsons correlation: 0.892
Pearsons correlation: 0.932
Pearsons correlation: 0.933
Pearsons correlation: 0.952
Pearsons correlation: 0.953
Pearsons correlation: 0.903
