In [75]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

In [76]:
# define a matrix
A = array([[1,2,3,4,5,6,7,8,9,10],
           [11,12,13,14,15,16,17,18,19,20],
           [21,22,23,24,25,26,27,28,29,30]])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [77]:
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

In [78]:
U

array([[-0.19101157,  0.89266338,  0.40824829],
       [-0.51371859,  0.26348917, -0.81649658],
       [-0.8364256 , -0.36568503,  0.40824829]])

In [79]:
s

array([9.69657342e+01, 7.25578339e+00, 5.43064394e-15])

In [80]:
Sigma

array([[9.69657342e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 7.25578339e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.43064394e-15, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

In [81]:
VT

array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
        -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242],
       [-0.71590327,  0.22125777,  0.35844894,  0.23137425,  0.12099174,
         0.27768425, -0.35015608,  0.05691924, -0.00338669, -0.19723014],
       [-0.03274747, -0.17891449, -0.37608172,  0.89207072, -0.08211107,
        -0.11995167,  0.02920549, -0.06831525, -0.05443306, -0.00872147],
       [-0.07588946, -0.05763181, -0.30552732, -0.08865234,  0.92223855,
        -0.12098055, -0.00525156, -0.09919877, -0.09845351, -0.07065325],
       [ 0.06629874,  0.08438747, -0.47449715, -0.0967393 , -0.08248279,
         0.8362855 ,  0.03555043, -0.13520148, -0.138849  , -0.09475243],
       [-0.33592049,  0.16549299,  0.06013546, -0.02444478, -0.06055817,
        -0.0839398 ,  0.85527901, -0.15616659

In [82]:
# select
n_elements = 1
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]

In [83]:
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)

[[ 4.47097996  4.76535855  5.05973714  5.35411573  5.64849431  5.9428729
   6.23725149  6.53163008  6.82600867  7.12038725]
 [12.02453586 12.81625622 13.60797659 14.39969695 15.19141732 15.98313768
  16.77485805 17.56657841 18.35829878 19.15001914]
 [19.57809176 20.8671539  22.15621604 23.44527818 24.73434032 26.02340247
  27.31246461 28.60152675 29.89058889 31.17965103]]


In [84]:
# transform
T = U.dot(Sigma)
print(T)

[[-18.52157747]
 [-49.81310011]
 [-81.10462276]]


In [85]:
T = A.dot(VT.T)
print(T)

[[-18.52157747]
 [-49.81310011]
 [-81.10462276]]


# Pseudoinverse

In [86]:
from numpy import array
from numpy.linalg import pinv

In [87]:
# define matrix
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])
print(A)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]


In [88]:
# calculate pseudoinverse
B = pinv(A)
print(B)

[[-1.00000000e+01 -5.00000000e+00  1.28757642e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


# Pseudoinverse via SVD

In [89]:
from numpy import array
from numpy.linalg import svd
from numpy import zeros
from numpy import diag

In [90]:
# define matrix
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])
print(A)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]


In [91]:
# calculate svd
U, s, VT = svd(A)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)
# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)
print(B)

[[-1.00000000e+01 -5.00000000e+00  1.28565458e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


## Scikit learn Truncated

In [67]:
from numpy import array
from sklearn.decomposition import TruncatedSVD

In [68]:
# define a matrix
A = array([[1,2,3,4,5,6,7,8,9,10],
           [11,12,13,14,15,16,17,18,19,20],
           [21,22,23,24,25,26,27,28,29,30]])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [69]:
# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print(result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
